### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by takos22** [2StepsFr0mHell/playground-fps9ganj#5]
Hey,
I saw that this repository was being committed to but the pages on the website aren’t updated. For example, the [tools file](https://github.com/CodinGame/Contribute-Help/blob/master/pages/community/tool.md) is updated but the [website](https://www.codingame.com/playgrounds/40701/contribute---help/codingamer-tool) isn’t. When will it be updated? 

PS: I made an [API wrapper in python](https://github.com/takos22/codingame) for the codingame API, so could you please add it in the list of community tools?

PS2: Do you have plans to write some docs for the API? If so, I'd be happy to help you write it.

**Comment by 2StepsFr0mHell** [comment]
Hello,

I'll soon publish the changes. This playground will become the official CodinGame FAQ. However, our API is not official, so there won't be any documentation. Sorry about that.
For now, your wrapper is indirectly listed through the forum link of resources. I may add a direct link to it on the tool page.
