### ISSUE TITLE
404 at forum link

### ISSUE THREAD

**Issue by eulerscheZahl** [2StepsFr0mHell/playground-fps9ganj#6]
https://github.com/CodinGame/Contribute-Help/blob/7e8cc5ebaec4ba4dc8ef60f9e03709819ad31de8/pages/community/tool.md#L45

This forum post has since been deleted.

**Comment by 2StepsFr0mHell** [comment]
Fixed, thanks
https://github.com/CodinGame/Contribute-Help/commit/aa43075ad9b40b58537edf5211da11fed658a4ad
